### ISSUE TITLE
Unable to login to custom instance

### ISSUE THREAD

**Issue by thetokenlady** [mani-sh-reddy/Lunar-Lemmy-iOS#230]
I can log in to my lemmy.world account, which is in the drop-down, but can’t log into either sh.itjust.works or Midwest.social when entering the instance address in the custom instance. No error message.

**Comment by mani-sh-reddy** [comment]
Hi, I've added more instances to the list in [0.8.67](https://github.com/mani-sh-reddy/Lunar/releases/tag/0.8.67) and have temporarily disabled custom instances. Just waiting on TestFlight approval.

**Comment by cryocaustik** [comment]
@mani-sh-reddy any updates on the custom instance option? Would love to try this app out, but being limited to the pre-selected instance list is a huge barrier.

**Comment by mani-sh-reddy** [comment]
Hey, this should be resolved now. 
Please add the instance first  in _settings -> manage instances_ and then try logging in.

Let me know what instance you're trying to login to if you're still facing problems.
