### ISSUE TITLE
Swipe to comment doesn't work.

### ISSUE THREAD

**Issue by lov3b** [mani-sh-reddy/Lunar-Lemmy-iOS#236]
When in a thread and you've swiped to get options for replying or collapsing a comment, the reply button won't do anything other than closing the menu.

https://github.com/mani-sh-reddy/Lunar/assets/51426041/962db94a-5546-49f5-abc8-ffec952ab582

**Comment by mani-sh-reddy** [comment]
Thanks for bringing this up, will release a fix soon

**Comment by lov3b** [comment]
No, thank you!

**Comment by mani-sh-reddy** [comment]
Fixed in [2023.11.2](https://github.com/mani-sh-reddy/Lunar/releases/tag/2023.11.2)


> [testflight.apple.com/join/GEFCCQTb](https://testflight.apple.com/join/GEFCCQTb)
